import type { Exercise } from './types';

export const EXERCISE_CATALOG: Exercise[] = [
  {
    slug: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    targetMuscles: ['quads', 'glutes', 'core'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    movementPattern: 'squat',
    instructions: [
      'Stand with feet about shoulder-width apart.',
      'Push hips back and bend knees until thighs are near parallel.',
      'Drive through mid-foot and stand tall without locking the knees.',
    ],
    coachTip: 'Keep the chest proud and knees tracking in line with your toes.',
  },
  {
    slug: 'push-up',
    name: 'Push-up',
    targetMuscles: ['chest', 'triceps', 'shoulders', 'core'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    movementPattern: 'push',
    instructions: [
      'Start in a high plank with hands under shoulders.',
      'Lower with elbows about 45 degrees from your body.',
      'Press the floor away until arms are straight.',
    ],
    coachTip: 'Use an incline if your hips sag or your reps get sloppy.',
  },
  {
    slug: 'dumbbell-goblet-squat',
    name: 'Dumbbell Goblet Squat',
    targetMuscles: ['quads', 'glutes', 'upper back'],
    equipment: ['dumbbells', 'home_gym', 'gym'],
    difficulty: 'beginner',
    movementPattern: 'squat',
    instructions: [
      'Hold one dumbbell vertically against your chest.',
      'Sit between your hips while keeping elbows inside the knees.',
      'Stand up by pushing the floor away.',
    ],
    coachTip: 'Pause for one second at the bottom to build control.',
  },
  {
    slug: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    targetMuscles: ['hamstrings', 'glutes', 'lower back'],
    equipment: ['dumbbells', 'home_gym', 'gym'],
    difficulty: 'intermediate',
    movementPattern: 'hinge',
    instructions: [
      'Hold dumbbells in front of thighs with soft knees.',
      'Hinge at the hips and slide dumbbells down the legs.',
      'Stop when hamstrings stretch, then squeeze glutes to stand.',
    ],
    coachTip: 'The hips move back; the knees should not turn it into a squat.',
  },
  {
    slug: 'band-row',
    name: 'Resistance Band Row',
    targetMuscles: ['lats', 'mid back', 'biceps'],
    equipment: ['bands', 'home_gym'],
    difficulty: 'beginner',
    movementPattern: 'pull',
    instructions: [
      'Anchor the band at chest height.',
      'Pull elbows behind ribs while keeping shoulders down.',
      'Return slowly until arms are straight.',
    ],
    coachTip: 'Start each rep by pulling shoulder blades back, not by shrugging.',
  },
  {
    slug: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    targetMuscles: ['chest', 'triceps', 'shoulders'],
    equipment: ['dumbbells', 'gym', 'home_gym'],
    difficulty: 'intermediate',
    movementPattern: 'push',
    instructions: [
      'Lie on a bench with dumbbells above chest.',
      'Lower until elbows are slightly below the torso.',
      'Press up and bring dumbbells over mid-chest.',
    ],
    coachTip: 'Keep shoulder blades pinned to the bench throughout the set.',
  },
  {
    slug: 'lat-pulldown',
    name: 'Lat Pulldown',
    targetMuscles: ['lats', 'upper back', 'biceps'],
    equipment: ['gym'],
    difficulty: 'beginner',
    movementPattern: 'pull',
    instructions: [
      'Grip the bar just outside shoulder width.',
      'Pull elbows down toward ribs until the bar reaches upper chest.',
      'Control the return without letting shoulders shrug up.',
    ],
    coachTip: 'Think elbows to pockets instead of bar to chest.',
  },
  {
    slug: 'walking-lunge',
    name: 'Walking Lunge',
    targetMuscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['bodyweight', 'dumbbells', 'gym', 'home_gym'],
    difficulty: 'intermediate',
    movementPattern: 'lunge',
    instructions: [
      'Step forward and lower until both knees bend near 90 degrees.',
      'Drive through the front foot to stand and step into the next rep.',
      'Alternate legs while keeping torso tall.',
    ],
    coachTip: 'Shorten your stride if your front knee collapses inward.',
  },
  {
    slug: 'plank',
    name: 'Forearm Plank',
    targetMuscles: ['core', 'glutes', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    movementPattern: 'core',
    instructions: [
      'Place elbows under shoulders and extend legs.',
      'Squeeze glutes and brace as if preparing for a punch.',
      'Hold a straight line from head to heels.',
    ],
    coachTip: 'Stop the set when your lower back starts to sag.',
  },
  {
    slug: 'barbell-deadlift',
    name: 'Barbell Deadlift',
    targetMuscles: ['hamstrings', 'glutes', 'back', 'core'],
    equipment: ['gym'],
    difficulty: 'advanced',
    movementPattern: 'hinge',
    instructions: [
      'Set mid-foot under the bar and grip just outside legs.',
      'Brace, pull slack from the bar, and push the floor away.',
      'Lock out with hips and knees together, then lower under control.',
    ],
    coachTip: 'If your back rounds before the bar moves, reduce load and rebuild the setup.',
  },
  {
    slug: 'overhead-press',
    name: 'Standing Overhead Press',
    targetMuscles: ['shoulders', 'triceps', 'core'],
    equipment: ['dumbbells', 'gym', 'home_gym'],
    difficulty: 'intermediate',
    movementPattern: 'push',
    instructions: [
      'Start with weights at shoulder height and ribs stacked over hips.',
      'Press overhead without leaning back.',
      'Lower to shoulders with control.',
    ],
    coachTip: 'Brace your abs before every rep to avoid turning it into a backbend.',
  },
  {
    slug: 'hip-thrust',
    name: 'Hip Thrust',
    targetMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: ['gym', 'home_gym', 'dumbbells'],
    difficulty: 'intermediate',
    movementPattern: 'hinge',
    instructions: [
      'Place upper back on a bench with feet planted.',
      'Drive hips up until knees, hips, and shoulders form a line.',
      'Pause at the top, then lower under control.',
    ],
    coachTip: 'Keep ribs down and finish with glutes, not the lower back.',
  },
];
