'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { 
  Zap, 
  Dumbbell, 
  Apple, 
  LineChart, 
  MessageSquare, 
  Sparkles, 
  CheckCircle2, 
  Activity, 
  Flame, 
  Target,
  ArrowRight,
  TrendingDown,
  ShieldAlert,
  Award,
  DollarSign,
  Briefcase,
  Users,
  Compass,
  Smile,
  ShieldCheck,
  Star,
  Send,
  PhoneCall
} from 'lucide-react';
import { localDb, UserProfile, WorkoutPlan, DietPlan, ProgressLog } from '@/lib/db';

// -------------------------------------------------------------
// TRANSLATION DICTIONARY (English & Hinglish)
// -------------------------------------------------------------
const TRANSLATIONS = {
  english: {
    // Hero
    heroBadge: "AI-Powered Fitness & Sports Platform",
    heroTitle1: "TRAIN.",
    heroTitle2: "PLAY.",
    heroTitle3: "PERFORM.",
    heroDesc: "India's smartest multi-sport platform — AI workout plans, AI diet plans, progress loggers, and a local Llama coach. From the gym floor to your home.",
    heroStats1: "10K+ Members",
    heroStats2: "AI Inference Locally",
    heroStats3: "₹99 Per Month",
    heroBtnStart: "Get Started — ₹99",
    heroBtnFeatures: "See AI Features",
    sportGym: "💪 Gym",
    sportBadminton: "🏸 Badminton",
    sportCricket: "🏏 Cricket",
    sportFootball: "⚽ Football",
    sportYoga: "🧘 Yoga",

    // Status Banner
    statusLive: "🏋️ Gym Companion is NOW LIVE on FitCore AI — members can sign up, track progress, and get custom AI workouts & diet plans today.",
    statusComing: "Coming soon: Badminton, Cricket, Football & Yoga support.",

    // Sports Section
    sportsEyebrow: "Sports & Companion Classes",
    sportsTitle: "ACTIVITIES COVERED",
    sportsDesc: "We are live with Gym companion features, and expanding to every athletic activity soon. One app for all your routines.",
    gymDesc: "Full weight tracking, AI workout checklists, daily macro meal planner, and chat trainer — all in one dashboard.",
    badmintonDesc: "Coaching schedules, slot logging, and court stamina drills tracker. Coming soon.",
    cricketDesc: "Net practice logs, bowling/batting drill trackers, and local club matches planner. Coming soon.",

    // Features Section
    featEyebrow: "Platform Features",
    featTitle: "SMART FEATURES BUILT IN",
    featDesc: "FitCore AI is a complete, proprietary personal fitness ecosystem. Everything you need to optimize progress, right in your pocket.",
    dashboardTitle: "Interactive Companion Dashboard",
    dashboardDesc: "Keep your training organized. Monitor today's workouts, caloric macro targets, and scale records at a glance.",
    aiWorkoutTitle: "AI Workout Generator",
    aiWorkoutDesc: "Custom workout splits generated by Llama 3.2 based on your experience, goals, and equipment. Clickable safety tips.",
    aiDietTitle: "AI Nutrition Planner",
    aiDietDesc: "7-day customized Indian meal plan aligned to your target calories, meals count, and food allergies.",
    otpTitle: "Password-less Phone Login",
    otpDesc: "Log in quickly and securely with your mobile phone number using MSG91 OTP authentication. No passwords needed.",
    attendanceTitle: "QR Code Attendance Check-in",
    attendanceDesc: "Scan your gym's unique QR code to check in, building streak counters and mapping calendar heatmaps.",
    alertsTitle: "Automated Expiry & Smart Alerts",
    alertsDesc: "Receive automated notifications on WhatsApp and SMS regarding plan expirations and motivational follow-ups.",
    walletTitle: "Wallet & Referral Credits",
    walletDesc: "Share your referral link to earn ₹100 inside your digital wallet. Redeem balance for renewals.",
    chatTitle: "AI Coach Desk Chatbot",
    chatDesc: "Ask our local Llama 3.2 model anything: form tips, nutrition alternatives, or workout progressions.",
    analyticsTitle: "Full Progress Analytics",
    analyticsDesc: "Log weight and body measurements weekly. Plot results in beautiful Area Charts using Recharts.",

    // How It Works
    howBadge: "Verified Gym Venues Only",
    howTitle: "HOW FITCORE AI WORKS",
    howDesc: "Every gym center and fitness studio undergoes manual validation before getting listed on the platform.",
    step1Title: "Owner Sends Request",
    step1Desc: "Gym owners sign up and request registration by sending their venue address, contact, and license info.",
    step2Title: "We Verify The Venue",
    step2Desc: "Our compliance team inspects the gym's credentials, equipment status, and local trainers.",
    step3Title: "Approval & Trial Code",
    step3Desc: "Once approved, a unique gym ID and attendance QR code are generated for the members.",
    step4Title: "Go Live & Track",
    step4Desc: "Members log in, scan the QR code to check in, and get localized AI fitness blueprints instantly.",

    // Single Plan Card
    pricingEyebrow: "Simple Pricing",
    pricingTitle: "ONE PLAN. EVERYTHING UNLOCKED.",
    pricingDesc: "No tiers, no surprises. Access all features — including AI generations — for one low price.",
    planBadge: "Launch Offer - 80% Off",
    planName: "FitCore AI All-Access",
    planStrike: "₹499/month",
    planPrice: "99",
    planPeriod: "Per Month • Cancel Anytime",
    feat1: "Unlimited AI Workouts Split Generator",
    feat2: "7-Day Custom Indian Diet Logs",
    feat3: "Interactive AI Coach Chatbot",
    feat4: "Weight & Measurement Progression Charts",
    feat5: "Wallet System & ₹100 Sign-up Bonus",
    planBtn: "Generate My AI Blueprint",

    // Testimonials
    revTitle: "WHAT OUR USERS SAY",
    rev1Text: "FitCore AI's Hinglish coach makes it so easy! Tips like 'back straight rakho' feel like a real trainer is talking to me. Smashed my weight goals.",
    rev2Text: "The local Ollama Llama 3.2 chatbot answers immediately. The Indian diet plan incorporates actual home food like paneer cheela and dal.",
    rev3Text: "Amazing progress charts. Uploading my weekly photos and logging measurements helped me stay consistent for 8 weeks straight.",

    // Enquiry
    enqTitle: "REGISTER YOUR GYM / COMPANION",
    enqDesc: "Are you a gym owner? List your venue to provide your members with QR check-ins, automated alerts, and custom AI plans.",
    enqFormTitle: "Enquire For Listing",
    enqFormDesc: "Fill in your venue parameters below.",
    lblGym: "Gym / Venue Name",
    lblCity: "City",
    lblPhone: "Owner Contact Number",
    lblType: "Facility Type",
    enqBtn: "Submit Registry Request",
    enqSuccess: "Thank you! Your registration request has been recorded. Our verification team will contact you within 24 hours.",
    lblSelectType: "Select Facility Type"
  },
  hinglish: {
    // Hero
    heroBadge: "AI-Powered Fitness & Sports Platform",
    heroTitle1: "TRAIN.",
    heroTitle2: "PLAY.",
    heroTitle3: "PERFORM.",
    heroDesc: "India ka sabse smart multi-sport platform — AI workout plans, AI diet plans, progress loggers aur local Llama coach. Gym floor se lekar ghar tak.",
    heroStats1: "10K+ Members Active",
    heroStats2: "In-house Local AI",
    heroStats3: "Sirf ₹99 Per Month",
    heroBtnStart: "Shuru Karein — ₹99",
    heroBtnFeatures: "AI Features Dekhein",
    sportGym: "💪 Gym Center",
    sportBadminton: "🏸 Badminton Court",
    sportCricket: "🏏 Cricket Pitch",
    sportFootball: "⚽ Football Turf",
    sportYoga: "🧘 Yoga Studio",

    // Status Banner
    statusLive: "🏋️ Gym Companion ab LIVE hai FitCore AI par — members sign up karke attendance track kar sakte hain aur custom AI plans pa sakte hain.",
    statusComing: "Jald hi aayega: Badminton, Cricket, Football aur Yoga support.",

    // Sports Section
    sportsEyebrow: "Sports & Classes",
    sportsTitle: "ACTIVITIES COVERED",
    sportsDesc: "Hum Gym companion features ke saath live hain, aur baaki activities ko jald hi platform par laa rahe hain. Sabhi routines ke liye ek hi app.",
    gymDesc: "Full weight tracking, AI workout checklist, daily macro meal planner aur chat trainer — sab kuch ek hi dashboard par.",
    badmintonDesc: "Coaching schedules, slot logs aur court stamina drills tracker. Jald hi aayega.",
    cricketDesc: "Net practice logs, bowling/batting drill trackers aur local match planner. Coming soon.",

    // Features Section
    featEyebrow: "Platform Features",
    featTitle: "SMART FEATURES BUILT IN",
    featDesc: "FitCore AI ek complete, proprietary personal fitness ecosystem hai. Progress track karne ke liye har jaruri tool aapke phone me.",
    dashboardTitle: "Interactive Dashboard",
    dashboardDesc: "Apne training schedule ko systematically manage karein. Aaj ke workouts, macro meal target aur weight records ek jagah dekhein.",
    aiWorkoutTitle: "AI Workout Generator",
    aiWorkoutDesc: "Llama 3.2 se generated custom workout splits. Aapke goal, experience aur equipment ke hisab se safe workout tips.",
    aiDietTitle: "AI Nutrition Planner",
    aiDietDesc: "Aapke targeted calories, meal counts aur allergies ke mutabik custom 7-day Indian meal plan.",
    otpTitle: "Password-less Phone Login",
    otpDesc: "Mobile number aur MSG91 OTP ke jariye secure aur instant login. Passwords yaad rakhne ki koi jhanjhat nahi.",
    attendanceTitle: "QR Code Attendance Check-in",
    attendanceDesc: "Apne gym ka unique QR code scan karke check-in karein aur apni daily workout streaks badhayein.",
    alertsTitle: "Automated Expiry & Smart Alerts",
    alertsDesc: "Plan validation khatam hone par aur hydration guidelines ke liye direct WhatsApp aur SMS alerts paayein.",
    walletTitle: "Wallet & Referral Credits",
    walletDesc: "Apna referral code friends ke saath share karke wallet me ₹100 kamaayein. Renewal ke waqt balance use karein.",
    chatTitle: "AI Coach Desk Chatbot",
    chatDesc: "Local Llama 3.2 model se kuch bhi puchhein: exercise form tips, diet alternatives aur progression advice.",
    analyticsTitle: "Full Progress Analytics",
    analyticsDesc: "Har week apna weight aur body measurements log karein. Recharts area charts me visual graph progression dekhein.",

    // How It Works
    howBadge: "Sirf Verified Gyms ke liye",
    howTitle: "HOW FITCORE AI WORKS",
    howDesc: "Platform par live jaane se pehle har gym center aur fitness studio ka manual verification kiya jata hai.",
    step1Title: "Owner Request Bhejte Hain",
    step1Desc: "Gym owners signup karke apne venue ka address, owner contact aur license details submit karte hain.",
    step2Title: "Hum Venue Verify Karte Hain",
    step2Desc: "Humari compliance team gym ke licenses, equipment aur trainers ki details verify karti hai.",
    step3Title: "Approval & QR Code Creation",
    step3Desc: "Verification complete hone par ek unique gym ID aur attendance QR code generate hota hai.",
    step4Title: "Live Jayein & Track Karein",
    step4Desc: "Members login karke QR code scan karte hain aur custom AI plans access karte hain.",

    // Single Plan Card
    pricingEyebrow: "Simple Pricing",
    pricingTitle: "ONE PLAN. EVERYTHING UNLOCKED.",
    pricingDesc: "Koi chupa hua charge nahi. Ek simple subscription plan me saare features aur unlimited AI generations unlocked.",
    planBadge: "Launch Offer - 80% Off",
    planName: "FitCore AI All-Access",
    planStrike: "₹499/month",
    planPrice: "99",
    planPeriod: "Per Month • Cancel Anytime",
    feat1: "Unlimited AI Workouts Split Generator",
    feat2: "7-Day Custom Indian Diet Logs",
    feat3: "Interactive AI Coach Chatbot",
    feat4: "Weight & Measurement Progression Charts",
    feat5: "Wallet System & ₹100 Sign-up Bonus",
    planBtn: "Apna AI Plan Generate Karein",

    // Testimonials
    revTitle: "WHAT OUR USERS SAY",
    rev1Text: "FitCore AI ka Hinglish coach bahut mast hai! 'back straight rakho' jaise guidelines se lagta hai ki koi personal trainer saath me hai.",
    rev2Text: "Local Ollama Llama 3.2 chatbot bina internet latency ke answer deta hai. Aur paneer cheela jaisa authentic Indian food diet plan me milta hai.",
    rev3Text: "Super progress charts! Har week photos upload karke aur measurements track karke maine 8 weeks me fat loss achieve kiya.",

    // Enquiry
    enqTitle: "APNE GYM KO REGISTER KAREIN",
    enqDesc: "Kya aap gym owner hain? Apne gym ko list karein aur members ko QR check-ins, automated alerts aur AI companion features dein.",
    enqFormTitle: "Listing Enquiry Karein",
    enqFormDesc: "Niche apne gym ki details fill karein.",
    lblGym: "Gym / Venue Ka Naam",
    lblCity: "City / City",
    lblPhone: "Owner Contact Number",
    lblType: "Facility Ka Type",
    enqBtn: "Registration Request Bhejte Hain",
    enqSuccess: "Dhanyawad! Aapki registration request register ho gayi hai. Humari team 24 ghante me aapko contact karei.",
    lblSelectType: "Facility Type Select Karein"
  }
};

export default function DashboardOrLanding() {
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [workoutPlan, setWorkoutPlan] = useState<WorkoutPlan | null>(null);
  const [dietPlan, setDietPlan] = useState<DietPlan | null>(null);
  const [latestLog, setLatestLog] = useState<ProgressLog | null>(null);
  const [todayStr, setTodayStr] = useState('');
  
  // Localization State
  const [lang, setLang] = useState<'english' | 'hinglish'>('english');
  
  // Registration Form States
  const [gymName, setGymName] = useState('');
  const [city, setCity] = useState('');
  const [phone, setPhone] = useState('');
  const [facilityType, setFacilityType] = useState('gym');
  const [formSubmitted, setFormSubmitted] = useState(false);

  useEffect(() => {
    const today = new Date().toISOString().split('T')[0];
    setTodayStr(today);
    
    // Load initial states
    const prof = localDb.getProfile();
    setProfile(prof);
    setLang(prof.language || 'english');
    
    setWorkoutPlan(localDb.getWorkoutPlan());
    setDietPlan(localDb.getDietPlan());
    
    const logs = localDb.getProgressLogs();
    if (logs.length > 0) {
      setLatestLog(logs[logs.length - 1]);
    }

    // Listen for language toggles in bottom right
    const handleLanguageToggle = (e: Event) => {
      const customEvent = e as CustomEvent;
      if (customEvent.detail) {
        setLang(customEvent.detail);
      } else {
        // Fallback to loading profile
        const p = localDb.getProfile();
        setLang(p.language || 'english');
      }
    };
    
    window.addEventListener('fitcore_language_changed', handleLanguageToggle);
    window.addEventListener('fitcore_profile_updated', () => {
      const p = localDb.getProfile();
      setProfile(p);
      setLang(p.language || 'english');
    });

    return () => {
      window.removeEventListener('fitcore_language_changed', handleLanguageToggle);
    };
  }, []);

  const handleEnquirySubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!gymName || !phone) return;
    
    // Save to local storage mock registry database
    const registrations = JSON.parse(localStorage.getItem('fitcore_gym_registrations') || '[]');
    registrations.push({
      gymName,
      city,
      phone,
      facilityType,
      date: new Date().toISOString()
    });
    localStorage.setItem('fitcore_gym_registrations', JSON.stringify(registrations));
    
    // Clear states
    setGymName('');
    setCity('');
    setPhone('');
    setFormSubmitted(true);
    
    setTimeout(() => {
      setFormSubmitted(false);
    }, 4000);
  };

  const getAiCoachAdvice = (goal: string) => {
    if (lang === 'hinglish') {
      switch(goal) {
        case 'weight loss':
          return "Coach Tip: Khana khane se 15 min pehle paani peeyein. Cardio ke sath heavy compound sets lagayein calories burn badhane ke liye.";
        case 'muscle gain':
          return "Coach Tip: Apni target protein intake badhayein. Subah ke breakfast me paneer ya egg whites shaamil karein.";
        case 'endurance':
          return "Coach Tip: Hydration ka poora dhyan rakhein. Workout ke baad breathing control drills lagayein stamina badhane ke liye.";
        case 'flexibility':
          return "Coach Tip: Stretching stretch ko 30 seconds hold karein. Cold muscles stretch bilkul na karein.";
        default:
          return "Coach Tip: Consistency hi sabse badi key hai. 20-minute ka workout bhi zero minute workout se behtar hai.";
      }
    } else {
      switch(goal) {
        case 'weight loss':
          return "Coach Tip: Drink 500ml water before meals. Keep training intensity high and use compound movements to maximize caloric output.";
        case 'muscle gain':
          return "Coach Tip: Prioritize protein synthesis. Ensure at least 30g protein during breakfast to kickstart muscle growth.";
        case 'endurance':
          return "Coach Tip: Maintain steady hydration. Implement interval training post-weights to build lung and heart capacity.";
        case 'flexibility':
          return "Coach Tip: Hold static stretches for 30s post-routine. Always stretch warm muscles to prevent injury.";
        default:
          return "Coach Tip: Consistency is the mother of mastery. A 20-minute session beats a zero-minute session.";
      }
    }
  };

  const hasPlans = workoutPlan && dietPlan;
  const t = TRANSLATIONS[lang];

  // -------------------------------------------------------------
  // RENDERING PART A: ACTIVE MEMBER DASHBOARD
  // -------------------------------------------------------------
  if (hasPlans) {
    const todayExercises = workoutPlan.plan_data[0]?.exercises || [];
    const completedTodayList = workoutPlan.completed_exercises?.[todayStr] || [];
    const exercisesCompletedCount = todayExercises.filter(ex => completedTodayList.includes(ex.name)).length;
    
    const dietDay = dietPlan.plan_data[0];
    const totalCals = 
      (dietDay?.breakfast?.calories || 0) + 
      (dietDay?.lunch?.calories || 0) + 
      (dietDay?.dinner?.calories || 0) + 
      (dietDay?.snacks?.calories || 0);
    const totalProtein = 
      (dietDay?.breakfast?.protein_g || 0) + 
      (dietDay?.lunch?.protein_g || 0) + 
      (dietDay?.dinner?.protein_g || 0) + 
      (dietDay?.snacks?.protein_g || 0);

    return (
      <div className="space-y-8 animate-[fadeIn_0.4s_ease-out]">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <h1 className="text-3xl font-extrabold tracking-tight text-white">
              {lang === 'hinglish' ? 'Hello,' : 'Hello,'} <span className="bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent">{profile?.name || 'Champion'}</span>!
            </h1>
            <p className="text-gray-400 text-sm mt-1">
              {lang === 'hinglish' ? 'Aaj ka workout checklist aur macro targets ready hain.' : 'Ready to dominate today? Here is your personalized fitness outlook.'}
            </p>
          </div>
          
          <div className="flex items-center gap-2 bg-white/5 border border-white/8 px-4 py-2 rounded-xl text-xs text-gray-300 font-semibold uppercase tracking-wider">
            <Target className="h-4 w-4 text-cyan-400 animate-pulse" />
            {lang === 'hinglish' ? 'Target:' : 'Target:'} {profile?.goal}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Workout Card */}
          <div className="glass-panel glass-panel-hover rounded-2xl p-6 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="flex justify-between items-start">
                <div className="h-10 w-10 bg-cyan-500/10 border border-cyan-500/20 rounded-xl flex items-center justify-center">
                  <Dumbbell className="h-5 w-5 text-cyan-400" />
                </div>
                <span className="text-[10px] bg-cyan-500/10 text-cyan-400 px-2 py-1 rounded-full font-bold uppercase tracking-wider">
                  Workout
                </span>
              </div>
              
              <div>
                <h3 className="text-lg font-bold text-white">{lang === 'hinglish' ? 'Aaj Ka AI Workout' : 'Today\'s AI Workout'}</h3>
                <p className="text-xs text-gray-400 mt-1">{profile?.equipment} setup companion</p>
              </div>
              
              <div className="flex items-center gap-2.5 text-xs text-gray-300 font-semibold">
                <CheckCircle2 className="h-4 w-4 text-cyan-400" />
                <span>{exercisesCompletedCount} of {todayExercises.length} Exercises Smashed</span>
              </div>
            </div>
            
            <Link 
              href="/workout" 
              className="mt-6 flex items-center gap-1.5 text-xs font-bold text-cyan-400 group hover:underline"
            >
              {lang === 'hinglish' ? 'Session Shuru Karein' : 'Start Session'}
              <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" />
            </Link>
          </div>

          {/* Diet Card */}
          <div className="glass-panel glass-panel-hover rounded-2xl p-6 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="flex justify-between items-start">
                <div className="h-10 w-10 bg-emerald-500/10 border border-emerald-500/20 rounded-xl flex items-center justify-center">
                  <Apple className="h-5 w-5 text-emerald-400" />
                </div>
                <span className="text-[10px] bg-emerald-500/10 text-emerald-400 px-2 py-1 rounded-full font-bold uppercase tracking-wider">
                  Nutrition
                </span>
              </div>
              
              <div>
                <h3 className="text-lg font-bold text-white">{lang === 'hinglish' ? 'Diet Khana-Peena' : 'Diet Breakdown'}</h3>
                <p className="text-xs text-gray-400 mt-1">Daily targeted meal structures</p>
              </div>

              <div className="flex gap-4 text-xs text-gray-300">
                <div className="flex items-center gap-1.5 font-semibold">
                  <Flame className="h-4 w-4 text-orange-500" />
                  <span>{totalCals} kcal</span>
                </div>
                <div className="flex items-center gap-1.5 font-semibold">
                  <Activity className="h-4 w-4 text-cyan-400" />
                  <span>{totalProtein}g Protein</span>
                </div>
              </div>
            </div>
            
            <Link 
              href="/diet" 
              className="mt-6 flex items-center gap-1.5 text-xs font-bold text-emerald-400 group hover:underline"
            >
              {lang === 'hinglish' ? 'Meal Plan Dekhein' : 'View Meal Plan'}
              <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" />
            </Link>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="glass-panel rounded-2xl p-6 flex flex-col justify-between lg:col-span-1">
            <div className="space-y-2">
              <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider block">Scale Stats</span>
              <h3 className="text-lg font-bold text-white">Bodyweight Logger</h3>
            </div>
            
            <div className="my-4 flex items-baseline gap-2">
              <span className="text-3xl font-black text-white">{latestLog ? `${latestLog.weight_kg} kg` : `${profile?.weight_kg || 'N/A'} kg`}</span>
              <span className="text-xs text-emerald-400 font-bold flex items-center gap-1">
                <TrendingDown className="h-3.5 w-3.5" />
                Active
              </span>
            </div>

            <Link
              href="/progress"
              className="flex items-center gap-1 text-xs font-bold text-purple-400 group hover:underline"
            >
              {lang === 'hinglish' ? 'Log Entries Dekhein' : 'Log Weight Entries'}
              <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" />
            </Link>
          </div>

          <div className="glass-panel rounded-2xl p-6 lg:col-span-2 space-y-4 flex flex-col justify-between">
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-cyan-400" />
                <h3 className="text-lg font-bold text-white">Coach Desk Bulletins</h3>
              </div>
              <p className="text-xs text-gray-400">Proactive recommendation based on your profile.</p>
            </div>

            <blockquote className="p-4 rounded-xl border border-white/5 bg-white/2 text-sm text-cyan-200 italic leading-relaxed">
              "{getAiCoachAdvice(profile?.goal || '')}"
            </blockquote>

            <Link
              href="/chat"
              className="w-fit flex items-center gap-1.5 text-xs font-bold text-cyan-400 hover:text-cyan-300 transition-colors"
            >
              {lang === 'hinglish' ? 'Coach se kuch puchhein' : 'Ask AI Coach a question'}
              <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </div>
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------
  // RENDERING PART B: DETAILED STARTUP LANDING PAGE
  // -------------------------------------------------------------
  return (
    <div className="space-y-20 animate-[fadeIn_0.5s_ease-out] max-w-5xl mx-auto px-1">
      
      {/* 1. HERO SECTION */}
      <section className="relative min-h-[85vh] flex flex-col justify-center items-start pt-10 overflow-hidden">
        <div className="absolute inset-0 -top-20 bg-gradient-radial-neon opacity-70 pointer-events-none -z-10" />
        
        <div className="max-w-3xl space-y-6">
          <div className="inline-flex items-center gap-2 bg-cyan-500/10 border border-cyan-500/20 px-4 py-2 rounded-full text-[10px] md:text-xs text-cyan-400 font-bold uppercase tracking-wider animate-pulse-neon">
            <Sparkles className="h-4 w-4" />
            {t.heroBadge}
          </div>
          
          <h1 className="text-5xl md:text-7xl font-black tracking-tight leading-[0.95] text-white">
            {t.heroTitle1}<br />
            <span className="text-cyan-400">{t.heroTitle2}</span><br />
            <span className="bg-gradient-to-r from-yellow-400 to-amber-500 bg-clip-text text-transparent">{t.heroTitle3}</span>
          </h1>
          
          <p className="text-gray-400 text-sm md:text-base max-w-xl leading-relaxed">
            {t.heroDesc}
          </p>

          <div className="flex flex-wrap gap-4 pt-2">
            <Link
              href="/profile"
              className="px-8 py-4 bg-gradient-to-r from-cyan-500 to-purple-500 text-white rounded-xl text-sm font-semibold hover:scale-[1.02] shadow-[0_0_20px_rgba(6,182,212,0.3)] hover:shadow-[0_0_30px_rgba(6,182,212,0.5)] transition-all flex items-center gap-2"
            >
              <Zap className="h-4.5 w-4.5 text-yellow-300" />
              {t.planBtn}
              <ArrowRight className="h-4 w-4" />
            </Link>
            
            <a
              href="#features"
              className="px-8 py-4 bg-white/5 border border-white/10 hover:border-white/20 text-gray-200 rounded-xl text-sm font-semibold hover:bg-white/8 transition-all"
            >
              {t.heroBtnFeatures}
            </a>
          </div>
        </div>

        {/* HERO STATS BAR */}
        <div className="grid grid-cols-3 gap-6 md:gap-12 mt-16 pt-8 border-t border-[rgba(255,255,255,0.06)] w-full">
          <div>
            <p className="text-xl md:text-3xl font-extrabold text-cyan-400">10K+</p>
            <p className="text-[10px] md:text-xs text-gray-400 uppercase tracking-wider font-semibold mt-1">{t.heroStats1}</p>
          </div>
          <div>
            <p className="text-xl md:text-3xl font-extrabold text-purple-400">Llama 3.2</p>
            <p className="text-[10px] md:text-xs text-gray-400 uppercase tracking-wider font-semibold mt-1">{t.heroStats2}</p>
          </div>
          <div>
            <p className="text-xl md:text-3xl font-extrabold text-yellow-400">₹99</p>
            <p className="text-[10px] md:text-xs text-gray-400 uppercase tracking-wider font-semibold mt-1">{t.heroStats3}</p>
          </div>
        </div>

        {/* SPORT PILLS SCROLL */}
        <div className="flex flex-wrap gap-2.5 mt-8 text-xs font-semibold text-gray-400">
          <span className="px-4 py-2 rounded-xl bg-white/3 border border-white/5 hover:border-cyan-400/20 hover:text-white transition-all cursor-pointer">{t.sportGym}</span>
          <span className="px-4 py-2 rounded-xl bg-white/3 border border-white/5 hover:border-cyan-400/20 hover:text-white transition-all cursor-pointer">{t.sportBadminton}</span>
          <span className="px-4 py-2 rounded-xl bg-white/3 border border-white/5 hover:border-cyan-400/20 hover:text-white transition-all cursor-pointer">{t.sportCricket}</span>
          <span className="px-4 py-2 rounded-xl bg-white/3 border border-white/5 hover:border-cyan-400/20 hover:text-white transition-all cursor-pointer">{t.sportFootball}</span>
          <span className="px-4 py-2 rounded-xl bg-white/3 border border-white/5 hover:border-cyan-400/20 hover:text-white transition-all cursor-pointer">{t.sportYoga}</span>
        </div>
      </section>

      {/* 2. LIVE STATUS BANNER */}
      <div className="p-5 rounded-2xl bg-gradient-to-r from-emerald-500/10 to-teal-500/3 border border-emerald-400/20 flex flex-col md:flex-row gap-4 items-start md:items-center">
        <div className="h-2.5 w-2.5 rounded-full bg-emerald-400 animate-ping shrink-0 shadow-[0_0_8px_#10b981] mt-1.5 md:mt-0" />
        <div className="space-y-1">
          <p className="text-xs md:text-sm font-semibold text-emerald-400">{t.statusLive}</p>
          <p className="text-[11px] text-gray-400">{t.statusComing}</p>
        </div>
      </div>

      {/* 3. ACTIVITIES COVERED */}
      <section id="activities" className="space-y-10">
        <div className="space-y-2">
          <span className="text-xs font-bold text-cyan-400 uppercase tracking-widest block">{t.sportsEyebrow}</span>
          <h2 className="text-3xl md:text-4xl font-extrabold text-white">{t.sportsTitle}</h2>
          <p className="text-gray-400 text-sm max-w-xl leading-relaxed">{t.sportsDesc}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="glass-panel rounded-2xl p-6 border-t-4 border-cyan-400 hover:scale-[1.01] transition-transform">
            <span className="text-3xl block mb-4">🏋️</span>
            <h4 className="text-base font-bold text-white uppercase tracking-wide">Gym & Fitness</h4>
            <p className="text-xs text-gray-400 mt-2 leading-relaxed">{t.gymDesc}</p>
            <span className="inline-flex items-center gap-1.5 mt-5 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 text-[10px] font-bold uppercase tracking-wider">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
              Live Now
            </span>
          </div>

          <div className="glass-panel rounded-2xl p-6 opacity-60 border-t-4 border-yellow-400">
            <span className="text-3xl block mb-4">🏸</span>
            <h4 className="text-base font-bold text-white uppercase tracking-wide">Badminton</h4>
            <p className="text-xs text-gray-400 mt-2 leading-relaxed">{t.badmintonDesc}</p>
            <span className="inline-block mt-5 px-3 py-1 rounded-full bg-yellow-500/10 text-yellow-400 text-[10px] font-bold uppercase tracking-wider">
              Soon
            </span>
          </div>

          <div className="glass-panel rounded-2xl p-6 opacity-60 border-t-4 border-purple-400">
            <span className="text-3xl block mb-4">🏏</span>
            <h4 className="text-base font-bold text-white uppercase tracking-wide">Cricket</h4>
            <p className="text-xs text-gray-400 mt-2 leading-relaxed">{t.cricketDesc}</p>
            <span className="inline-block mt-5 px-3 py-1 rounded-full bg-purple-500/10 text-purple-400 text-[10px] font-bold uppercase tracking-wider">
              Soon
            </span>
          </div>
        </div>
      </section>

      {/* 4. SMART FEATURES GRID (BUILD LIKE MYFITPRO FEATURES) */}
      <section id="features" className="space-y-12">
        <div className="space-y-3">
          <div className="inline-flex items-center gap-1.5 bg-purple-500/10 border border-purple-500/20 text-purple-400 px-3.5 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-wider">
            <Users className="h-3.5 w-3.5" />
            {t.featEyebrow}
          </div>
          <h2 className="text-3xl md:text-5xl font-black text-white">{t.featTitle}</h2>
          <p className="text-gray-400 text-sm max-w-xl">{t.featDesc}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          
          <div className="glass-panel rounded-2xl p-6 space-y-3 border border-purple-500/20">
            <span className="text-2xl">🤖</span>
            <h4 className="text-sm font-bold text-white">{t.aiWorkoutTitle}</h4>
            <p className="text-xs text-gray-400 leading-relaxed">{t.aiWorkoutDesc}</p>
            <span className="inline-block px-2.5 py-1 rounded-full bg-purple-500/10 text-purple-400 text-[9px] font-bold uppercase tracking-wider">AI Powered</span>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-3 border border-purple-500/20">
            <span className="text-2xl">🥗</span>
            <h4 className="text-sm font-bold text-white">{t.aiDietTitle}</h4>
            <p className="text-xs text-gray-400 leading-relaxed">{t.aiDietDesc}</p>
            <span className="inline-block px-2.5 py-1 rounded-full bg-purple-500/10 text-purple-400 text-[9px] font-bold uppercase tracking-wider">AI Powered</span>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-3 border border-purple-500/20">
            <span className="text-2xl">💬</span>
            <h4 className="text-sm font-bold text-white">{t.chatTitle}</h4>
            <p className="text-xs text-gray-400 leading-relaxed">{t.chatDesc}</p>
            <span className="inline-block px-2.5 py-1 rounded-full bg-purple-500/10 text-purple-400 text-[9px] font-bold uppercase tracking-wider">AI Powered</span>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-3">
            <span className="text-2xl">📲</span>
            <h4 className="text-sm font-bold text-white">{t.otpTitle}</h4>
            <p className="text-xs text-gray-400 leading-relaxed">{t.otpDesc}</p>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-3">
            <span className="text-2xl">✅</span>
            <h4 className="text-sm font-bold text-white">{t.attendanceTitle}</h4>
            <p className="text-xs text-gray-400 leading-relaxed">{t.attendanceDesc}</p>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-3">
            <span className="text-2xl">📊</span>
            <h4 className="text-sm font-bold text-white">{t.analyticsTitle}</h4>
            <p className="text-xs text-gray-400 leading-relaxed">{t.analyticsDesc}</p>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-3">
            <span className="text-2xl">💳</span>
            <h4 className="text-sm font-bold text-white">{t.walletTitle}</h4>
            <p className="text-xs text-gray-400 leading-relaxed">{t.walletDesc}</p>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-3">
            <span className="text-2xl">🔔</span>
            <h4 className="text-sm font-bold text-white">{t.alertsTitle}</h4>
            <p className="text-xs text-gray-400 leading-relaxed">{t.alertsDesc}</p>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-3">
            <span className="text-2xl">💻</span>
            <h4 className="text-sm font-bold text-white">{t.dashboardTitle}</h4>
            <p className="text-xs text-gray-400 leading-relaxed">{t.dashboardDesc}</p>
          </div>

        </div>
      </section>

      {/* 5. HOW IT WORKS (STEPS LAYOUT) */}
      <section id="how" className="space-y-12">
        <div className="text-center space-y-3">
          <div className="inline-flex items-center gap-1.5 bg-yellow-500/10 border border-yellow-500/20 text-yellow-400 px-4 py-2 rounded-full text-xs font-bold uppercase tracking-wide">
            <ShieldAlert className="h-4 w-4" />
            {t.howBadge}
          </div>
          <h2 className="text-3xl md:text-5xl font-black text-white">{t.howTitle}</h2>
          <p className="text-gray-400 text-sm max-w-lg mx-auto">{t.howDesc}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-2">
          
          <div className="glass-panel rounded-2xl p-6 space-y-4">
            <p className="text-4xl font-extrabold text-cyan-500/10 leading-none">01</p>
            <span className="text-xl block">📨</span>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">{t.step1Title}</h4>
            <p className="text-[11px] text-gray-400 leading-relaxed">{t.step1Desc}</p>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-4 border-t-2 border-yellow-500/30">
            <p className="text-4xl font-extrabold text-yellow-500/10 leading-none">02</p>
            <span className="text-xl block">🔍</span>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">{t.step2Title}</h4>
            <p className="text-[11px] text-gray-400 leading-relaxed">{t.step2Desc}</p>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-4 border-t-2 border-yellow-500/30">
            <p className="text-4xl font-extrabold text-yellow-500/10 leading-none">03</p>
            <span className="text-xl block">✅</span>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">{t.step3Title}</h4>
            <p className="text-[11px] text-gray-400 leading-relaxed">{t.step3Desc}</p>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-4 border-t-2 border-emerald-500/30">
            <p className="text-4xl font-extrabold text-emerald-500/10 leading-none">04</p>
            <span className="text-xl block">🚀</span>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">{t.step4Title}</h4>
            <p className="text-[11px] text-gray-400 leading-relaxed">{t.step4Desc}</p>
          </div>

        </div>
      </section>

      {/* 6. SINGLE PRICING CARD */}
      <section id="pricing" className="space-y-12">
        <div className="text-center space-y-3">
          <span className="text-xs font-bold text-cyan-400 uppercase tracking-widest block">{t.pricingEyebrow}</span>
          <h2 className="text-3xl md:text-5xl font-black text-white">{t.pricingTitle}</h2>
          <p className="text-gray-400 text-sm max-w-md mx-auto">{t.pricingDesc}</p>
        </div>

        <div className="max-w-md mx-auto">
          <div className="relative rounded-3xl p-8 bg-gradient-to-tr from-[#160a0d] to-white/3 border border-cyan-500/30 shadow-2xl space-y-6 overflow-hidden">
            <div className="absolute top-0 right-0 h-40 w-40 bg-cyan-500/10 blur-3xl rounded-full" />
            
            <div className="text-center space-y-2">
              <span className="inline-block px-3.5 py-1.5 bg-cyan-500 text-black font-black text-[10px] rounded-full uppercase tracking-wider">
                {t.planBadge}
              </span>
              <h3 className="text-lg font-bold text-gray-300 uppercase tracking-wider mt-4">{t.planName}</h3>
              <p className="text-sm text-gray-500 line-through">{t.planStrike}</p>
              <p className="text-6xl font-black text-white leading-none">
                <span className="text-2xl font-semibold text-gray-400 align-super">₹</span>
                {t.planPrice}
              </p>
              <p className="text-xs text-gray-400 font-medium tracking-wide">{t.planPeriod}</p>
            </div>

            <ul className="text-xs text-gray-300 space-y-3.5 border-t border-b border-white/5 py-6">
              <li className="flex items-start gap-2.5">
                <CheckCircle2 className="h-4.5 w-4.5 text-cyan-400 shrink-0 mt-0.5" />
                <span>{t.feat1}</span>
              </li>
              <li className="flex items-start gap-2.5">
                <CheckCircle2 className="h-4.5 w-4.5 text-cyan-400 shrink-0 mt-0.5" />
                <span>{t.feat2}</span>
              </li>
              <li className="flex items-start gap-2.5">
                <CheckCircle2 className="h-4.5 w-4.5 text-cyan-400 shrink-0 mt-0.5" />
                <span>{t.feat3}</span>
              </li>
              <li className="flex items-start gap-2.5">
                <CheckCircle2 className="h-4.5 w-4.5 text-cyan-400 shrink-0 mt-0.5" />
                <span>{t.feat4}</span>
              </li>
              <li className="flex items-start gap-2.5">
                <CheckCircle2 className="h-4.5 w-4.5 text-cyan-400 shrink-0 mt-0.5" />
                <span>{t.feat5}</span>
              </li>
            </ul>

            <Link
              href="/profile"
              className="block w-full py-4 text-center bg-cyan-500 hover:bg-cyan-400 text-black font-extrabold text-sm rounded-xl transition-all shadow-[0_0_15px_rgba(6,182,212,0.3)] hover:scale-[1.01]"
            >
              {t.planBtn}
            </Link>
          </div>
        </div>
      </section>

      {/* 7. REVIEWS & TESTIMONIALS */}
      <section id="reviews" className="space-y-10">
        <h2 className="text-center text-xl md:text-2xl font-bold text-white tracking-wide">{t.revTitle}</h2>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="glass-panel rounded-2xl p-6 space-y-4">
            <div className="flex text-yellow-400 text-xs tracking-wider">★★★★★</div>
            <p className="text-xs text-gray-300 italic leading-relaxed">"{t.rev1Text}"</p>
            <div className="flex items-center gap-2">
              <div className="h-8 w-8 rounded-full bg-gradient-to-tr from-cyan-500 to-purple-500 flex items-center justify-center font-bold text-white text-xs">A</div>
              <div>
                <p className="text-xs font-bold text-white">Aniket Sharma</p>
                <p className="text-[10px] text-gray-500">Delhi, Gym Member</p>
              </div>
            </div>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-4">
            <div className="flex text-yellow-400 text-xs tracking-wider">★★★★★</div>
            <p className="text-xs text-gray-300 italic leading-relaxed">"{t.rev2Text}"</p>
            <div className="flex items-center gap-2">
              <div className="h-8 w-8 rounded-full bg-gradient-to-tr from-cyan-500 to-purple-500 flex items-center justify-center font-bold text-white text-xs">P</div>
              <div>
                <p className="text-xs font-bold text-white">Pooja Patel</p>
                <p className="text-[10px] text-gray-500">Mumbai, Fitness Enthusiast</p>
              </div>
            </div>
          </div>

          <div className="glass-panel rounded-2xl p-6 space-y-4">
            <div className="flex text-yellow-400 text-xs tracking-wider">★★★★★</div>
            <p className="text-xs text-gray-300 italic leading-relaxed">"{t.rev3Text}"</p>
            <div className="flex items-center gap-2">
              <div className="h-8 w-8 rounded-full bg-gradient-to-tr from-cyan-500 to-purple-500 flex items-center justify-center font-bold text-white text-xs">R</div>
              <div>
                <p className="text-xs font-bold text-white">Rohan Das</p>
                <p className="text-[10px] text-gray-500">Kolkata, Advanced Athlete</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 8. ENQUIRY REGISTER FORM */}
      <section id="enquiry" className="grid grid-cols-1 md:grid-cols-2 gap-10 items-start">
        <div className="space-y-4">
          <h2 className="text-3xl font-extrabold text-white">{t.enqTitle}</h2>
          <p className="text-gray-400 text-xs leading-relaxed">{t.enqDesc}</p>
          
          <div className="flex flex-col gap-3.5 pt-4">
            <a href="tel:+919043578159" className="flex items-center gap-3 p-4 rounded-xl border border-white/5 bg-white/2 hover:border-cyan-400/30 transition-all group">
              <PhoneCall className="h-5 w-5 text-cyan-400 group-hover:scale-110 transition-transform" />
              <div>
                <span className="text-[9px] text-gray-500 uppercase tracking-widest block">Call Support Hotline</span>
                <span className="text-xs font-bold text-white">+91 90435 78159</span>
              </div>
            </a>
            <a href="https://wa.me/919043578159" className="flex items-center gap-3 p-4 rounded-xl border border-emerald-500/10 bg-emerald-500/3 hover:border-emerald-400/30 transition-all group">
              <MessageSquare className="h-5 w-5 text-emerald-400 group-hover:scale-110 transition-transform" />
              <div>
                <span className="text-[9px] text-gray-500 uppercase tracking-widest block">WhatsApp Registration desk</span>
                <span className="text-xs font-bold text-white">Send "INTERESTED"</span>
              </div>
            </a>
          </div>
        </div>

        {/* Dynamic Enquiry Form */}
        <div className="glass-panel border-white/10 rounded-2xl p-6 md:p-8 space-y-6">
          <div>
            <h3 className="text-lg font-bold text-white">{t.enqFormTitle}</h3>
            <p className="text-[11px] text-gray-400 mt-1">{t.enqFormDesc}</p>
          </div>

          {formSubmitted ? (
            <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs leading-relaxed animate-[scaleIn_0.3s_ease]">
              {t.enqSuccess}
            </div>
          ) : (
            <form onSubmit={handleEnquirySubmit} className="space-y-4">
              <div className="space-y-1.5">
                <label className="block text-[10px] font-semibold text-gray-400 uppercase tracking-wider">{t.lblGym} *</label>
                <input 
                  type="text" 
                  value={gymName}
                  onChange={(e) => setGymName(e.target.value)}
                  required
                  placeholder="e.g. Gold's Gym South"
                  className="w-full bg-[#0b0e14] border border-white/8 focus:border-cyan-500 rounded-xl px-4 py-2.5 text-xs text-white outline-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <label className="block text-[10px] font-semibold text-gray-400 uppercase tracking-wider">{t.lblCity}</label>
                  <input 
                    type="text" 
                    value={city}
                    onChange={(e) => setCity(e.target.value)}
                    placeholder="e.g. Pune"
                    className="w-full bg-[#0b0e14] border border-white/8 focus:border-cyan-500 rounded-xl px-4 py-2.5 text-xs text-white outline-none"
                  />
                </div>
                
                <div className="space-y-1.5">
                  <label className="block text-[10px] font-semibold text-gray-400 uppercase tracking-wider">{t.lblType}</label>
                  <select 
                    value={facilityType}
                    onChange={(e) => setFacilityType(e.target.value)}
                    className="w-full bg-[#0b0e14] border border-white/8 focus:border-cyan-500 rounded-xl px-4 py-2.5 text-xs text-white outline-none font-medium"
                  >
                    <option value="gym">{t.sportGym}</option>
                    <option value="badminton">{t.sportBadminton}</option>
                    <option value="cricket">{t.sportCricket}</option>
                    <option value="football">{t.sportFootball}</option>
                    <option value="yoga">{t.sportYoga}</option>
                  </select>
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="block text-[10px] font-semibold text-gray-400 uppercase tracking-wider">{t.lblPhone} *</label>
                <input 
                  type="tel" 
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  required
                  placeholder="e.g. +91 98765 43210"
                  className="w-full bg-[#0b0e14] border border-white/8 focus:border-cyan-500 rounded-xl px-4 py-2.5 text-xs text-white outline-none"
                />
              </div>

              <button
                type="submit"
                className="w-full py-3.5 bg-cyan-500 hover:bg-cyan-400 text-black font-extrabold text-xs uppercase tracking-wider rounded-xl transition-all shadow-[0_0_15px_rgba(6,182,212,0.2)] flex items-center justify-center gap-2"
              >
                <Send className="h-4 w-4" />
                {t.enqBtn}
              </button>
            </form>
          )}
        </div>
      </section>

      {/* FOOTER BAND */}
      <footer className="pt-8 border-t border-white/5 flex flex-col sm:flex-row justify-between items-center gap-4 text-xs text-gray-500 pb-10">
        <span className="font-bold tracking-wider text-cyan-400 flex items-center gap-1.5">
          <Zap className="h-4 w-4" />
          FITCORE AI
        </span>
        <p>© 2026 FitCore AI. All rights reserved. Proprietary Protected.</p>
      </footer>
      
    </div>
  );
}
