import type { Exercise } from './types';

export const EXERCISES: Exercise[] = [
  {
    id: 'ex_incline_db_press',
    slug: 'incline-dumbbell-press',
    name: 'Incline dumbbell press',
    description: 'A supported pressing movement that biases the upper chest while training the front shoulders and triceps.',
    primaryMuscles: ['upper-chest', 'chest'],
    secondaryMuscles: ['front-deltoids', 'triceps'],
    equipment: ['Dumbbells', 'Bench'], difficulty: 'intermediate', category: 'hypertrophy', movementPattern: 'push', trainingType: 'compound', locations: ['gym', 'home'],
    instructions: ['Set the bench to a low incline of about 20–30 degrees.', 'Plant both feet and hold the dumbbells just outside your upper chest.', 'Press up and slightly inward without banging the weights together.', 'Lower with control until your elbows sit just below your torso.'],
    breathing: 'Inhale during the controlled lowering phase and exhale as you press.',
    formTips: ['Keep shoulder blades gently pulled down and back.', 'Stack wrists over elbows throughout the press.'],
    commonMistakes: ['Using an overly steep bench angle', 'Flaring the elbows straight out', 'Bouncing out of the bottom position'],
    safetyTips: ['Use a weight you can lower under control.', 'Ask for a spotter when training close to failure.'],
    easierVariation: 'Incline push-up', harderVariation: 'Alternating incline dumbbell press', setsRecommendation: '3–4 sets', repsRecommendation: '8–12 reps', restRecommendation: '75–120 sec', tags: ['upper body', 'chest', 'dumbbell'], demoStyle: 'push',
  },
  {
    id: 'ex_push_up', slug: 'push-up', name: 'Push-up', description: 'A scalable bodyweight press for the chest, triceps, shoulders, and trunk.',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'front-deltoids', 'upper-abs'], equipment: ['Bodyweight'], difficulty: 'beginner', category: 'strength', movementPattern: 'push', trainingType: 'compound', locations: ['home', 'gym'],
    instructions: ['Place hands slightly wider than shoulder width.', 'Brace your trunk so the body forms one long line.', 'Lower your chest between your hands with elbows angled back.', 'Push the floor away until your arms are straight.'],
    breathing: 'Inhale down and exhale through the press.', formTips: ['Keep ribs tucked.', 'Move your chest and hips together.'], commonMistakes: ['Dropping the hips', 'Shortening the range', 'Shrugging toward the ears'], safetyTips: ['Use an elevated surface if full range irritates the shoulder or wrist.'], easierVariation: 'Hands-elevated push-up', harderVariation: 'Feet-elevated push-up', setsRecommendation: '3–5 sets', repsRecommendation: '6–20 reps', restRecommendation: '60–90 sec', tags: ['bodyweight', 'home', 'push'], demoStyle: 'push',
  },
  {
    id: 'ex_shoulder_press', slug: 'seated-dumbbell-shoulder-press', name: 'Seated dumbbell shoulder press', description: 'A stable overhead press that develops the shoulders and triceps.',
    primaryMuscles: ['shoulders', 'front-deltoids'], secondaryMuscles: ['side-deltoids', 'triceps'], equipment: ['Dumbbells', 'Bench'], difficulty: 'intermediate', category: 'strength', movementPattern: 'push', trainingType: 'compound', locations: ['home', 'gym'],
    instructions: ['Sit against a near-upright backrest with feet planted.', 'Start with weights near ear height and forearms vertical.', 'Press overhead while keeping your ribs stacked.', 'Lower slowly to the start position.'], breathing: 'Exhale overhead and inhale while lowering.', formTips: ['Avoid over-arching the lower back.', 'Finish with biceps near the ears.'], commonMistakes: ['Using leg drive', 'Letting wrists bend backward', 'Cutting the lowering phase short'], safetyTips: ['Use a neutral grip if it feels better on the shoulders.'], easierVariation: 'Single-arm half-kneeling press', harderVariation: 'Standing dumbbell press', setsRecommendation: '3–4 sets', repsRecommendation: '6–12 reps', restRecommendation: '90 sec', tags: ['shoulders', 'dumbbell', 'press'], demoStyle: 'push',
  },
  {
    id: 'ex_lateral_raise', slug: 'dumbbell-lateral-raise', name: 'Dumbbell lateral raise', description: 'An isolation exercise for building the side deltoids and shoulder width.',
    primaryMuscles: ['side-deltoids'], secondaryMuscles: ['shoulders', 'traps'], equipment: ['Dumbbells'], difficulty: 'beginner', category: 'hypertrophy', movementPattern: 'push', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Stand tall with light dumbbells at your sides.', 'Lead with your elbows and raise the arms in a slight forward arc.', 'Pause near shoulder height.', 'Lower slowly without resting between reps.'], breathing: 'Exhale as the arms rise; inhale as they lower.', formTips: ['Keep a soft elbow bend.', 'Use a controlled two-second lowering phase.'], commonMistakes: ['Shrugging the weights up', 'Swinging from the hips', 'Using weight that is too heavy'], safetyTips: ['Stop below shoulder height if higher ranges pinch.'], easierVariation: 'One-arm supported lateral raise', harderVariation: 'Lean-away lateral raise', setsRecommendation: '3–4 sets', repsRecommendation: '12–20 reps', restRecommendation: '45–75 sec', tags: ['shoulders', 'isolation', 'dumbbell'], demoStyle: 'raise',
  },
  {
    id: 'ex_reverse_fly', slug: 'band-reverse-fly', name: 'Band reverse fly', description: 'A shoulder-friendly pull for the rear deltoids and upper back.',
    primaryMuscles: ['rear-deltoids', 'upper-back'], secondaryMuscles: ['traps'], equipment: ['Resistance band'], difficulty: 'beginner', category: 'hypertrophy', movementPattern: 'pull', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Hold the band at chest height with arms long.', 'Keep ribs down and pull the hands apart.', 'Pause when the band reaches your chest.', 'Return slowly without losing tension.'], breathing: 'Exhale as you pull apart and inhale on the return.', formTips: ['Move from the shoulder blades.', 'Keep shoulders away from the ears.'], commonMistakes: ['Bending the elbows excessively', 'Leaning back', 'Snapping the band on the return'], safetyTips: ['Inspect the band for damage before use.'], easierVariation: 'Lighter band pull-apart', harderVariation: 'Bent-over dumbbell reverse fly', setsRecommendation: '3 sets', repsRecommendation: '12–20 reps', restRecommendation: '45–60 sec', tags: ['band', 'posture', 'rear delts'], demoStyle: 'pull',
  },
  {
    id: 'ex_curl', slug: 'alternating-dumbbell-curl', name: 'Alternating dumbbell curl', description: 'A simple elbow-flexion exercise for the biceps and forearms.',
    primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'], equipment: ['Dumbbells'], difficulty: 'beginner', category: 'hypertrophy', movementPattern: 'pull', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Stand tall with palms facing forward.', 'Curl one dumbbell without moving the upper arm.', 'Squeeze briefly at the top.', 'Lower fully, then repeat on the other side.'], breathing: 'Exhale on the curl and inhale while lowering.', formTips: ['Pin elbows near your ribs.', 'Own the full lowering phase.'], commonMistakes: ['Swinging the torso', 'Letting elbows drift forward', 'Stopping short of full extension'], safetyTips: ['Keep the wrist neutral rather than curled backward.'], easierVariation: 'Resistance-band curl', harderVariation: 'Incline dumbbell curl', setsRecommendation: '3–4 sets', repsRecommendation: '8–15 reps', restRecommendation: '60 sec', tags: ['arms', 'biceps', 'dumbbell'], demoStyle: 'pull',
  },
  {
    id: 'ex_triceps', slug: 'overhead-dumbbell-triceps-extension', name: 'Overhead triceps extension', description: 'A long-range triceps exercise that emphasizes the long head.',
    primaryMuscles: ['triceps'], secondaryMuscles: ['shoulders'], equipment: ['Dumbbell'], difficulty: 'beginner', category: 'hypertrophy', movementPattern: 'push', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Hold one dumbbell securely overhead.', 'Keep elbows pointed mostly forward.', 'Lower the weight behind your head with control.', 'Extend the elbows without flaring the ribs.'], breathing: 'Inhale during the lowering phase and exhale as the elbows extend.', formTips: ['Keep the upper arms still.', 'Brace the abdomen.'], commonMistakes: ['Arching the back', 'Letting elbows flare wide', 'Moving too quickly'], safetyTips: ['Use two lighter dumbbells if holding one feels unstable.'], easierVariation: 'Band press-down', harderVariation: 'Single-arm overhead extension', setsRecommendation: '3 sets', repsRecommendation: '10–15 reps', restRecommendation: '60 sec', tags: ['arms', 'triceps', 'dumbbell'], demoStyle: 'push',
  },
  {
    id: 'ex_wrist_curl', slug: 'seated-wrist-curl', name: 'Seated wrist curl', description: 'A controlled forearm isolation movement for grip-supporting strength.',
    primaryMuscles: ['forearms'], secondaryMuscles: [], equipment: ['Dumbbells'], difficulty: 'beginner', category: 'strength', movementPattern: 'pull', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Rest your forearms on your thighs with palms up.', 'Let the dumbbells roll toward the fingers slightly.', 'Curl the wrists through a comfortable range.', 'Lower slowly and repeat.'], breathing: 'Breathe naturally and avoid holding your breath.', formTips: ['Keep forearms planted.', 'Use light weight and smooth reps.'], commonMistakes: ['Moving the elbows', 'Using a jerky range', 'Loading too heavily'], safetyTips: ['Stop if you feel sharp wrist discomfort.'], easierVariation: 'Towel squeeze', harderVariation: 'Behind-the-back barbell wrist curl', setsRecommendation: '2–3 sets', repsRecommendation: '15–25 reps', restRecommendation: '45 sec', tags: ['forearms', 'grip', 'dumbbell'], demoStyle: 'pull',
  },
  {
    id: 'ex_dead_bug', slug: 'dead-bug', name: 'Dead bug', description: 'A low-impact core drill that teaches trunk control while the limbs move.',
    primaryMuscles: ['upper-abs', 'lower-abs'], secondaryMuscles: ['hip-flexors'], equipment: ['Bodyweight', 'Mat'], difficulty: 'beginner', category: 'strength', movementPattern: 'core', trainingType: 'compound', locations: ['home', 'gym'],
    instructions: ['Lie on your back with hips and knees at 90 degrees.', 'Press your lower back gently into the floor.', 'Reach one arm and the opposite leg away.', 'Return with control and alternate sides.'], breathing: 'Exhale slowly as the limbs extend; inhale as they return.', formTips: ['Shorten the range before the back lifts.', 'Move slowly enough to feel the trunk working.'], commonMistakes: ['Arching the lower back', 'Rushing each side', 'Holding the breath'], safetyTips: ['Keep the head down if neck tension develops.'], easierVariation: 'Heel tap', harderVariation: 'Band-resisted dead bug', setsRecommendation: '3 sets', repsRecommendation: '6–10/side', restRecommendation: '45 sec', tags: ['core', 'bodyweight', 'beginner'], demoStyle: 'core',
  },
  {
    id: 'ex_reverse_crunch', slug: 'reverse-crunch', name: 'Reverse crunch', description: 'A spinal-flexion core exercise that trains the lower portion of the rectus abdominis.',
    primaryMuscles: ['lower-abs'], secondaryMuscles: ['upper-abs', 'hip-flexors'], equipment: ['Bodyweight', 'Mat'], difficulty: 'beginner', category: 'hypertrophy', movementPattern: 'core', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Lie down with knees bent above your hips.', 'Brace and curl your pelvis toward your ribs.', 'Lift the tailbone only a few centimetres.', 'Lower slowly without swinging the legs.'], breathing: 'Exhale during the curl and inhale while lowering.', formTips: ['Think pelvis to ribs, not knees to face.', 'Keep the movement small and controlled.'], commonMistakes: ['Using leg momentum', 'Rolling too far onto the neck', 'Losing tension at the bottom'], safetyTips: ['Use a mat and avoid pulling on the head.'], easierVariation: 'Bent-knee heel slide', harderVariation: 'Hanging knee raise', setsRecommendation: '3 sets', repsRecommendation: '10–15 reps', restRecommendation: '45–60 sec', tags: ['abs', 'bodyweight', 'core'], demoStyle: 'core',
  },
  {
    id: 'ex_side_plank', slug: 'side-plank', name: 'Side plank', description: 'An anti-lateral-flexion hold for the obliques, hips, and shoulder stabilizers.',
    primaryMuscles: ['obliques'], secondaryMuscles: ['abductors', 'shoulders'], equipment: ['Bodyweight', 'Mat'], difficulty: 'beginner', category: 'strength', movementPattern: 'core', trainingType: 'compound', locations: ['home', 'gym'],
    instructions: ['Place your elbow below your shoulder.', 'Stack or stagger your feet.', 'Lift the hips until the body forms a straight line.', 'Hold while breathing calmly, then switch sides.'], breathing: 'Take slow breaths while keeping the brace.', formTips: ['Push the floor away.', 'Keep hips stacked instead of rolling forward.'], commonMistakes: ['Letting the hips sag', 'Shrugging the support shoulder', 'Holding the breath'], safetyTips: ['Use a bent-knee version if the shoulder or back feels strained.'], easierVariation: 'Bent-knee side plank', harderVariation: 'Star side plank', setsRecommendation: '2–3 sets', repsRecommendation: '20–45 sec/side', restRecommendation: '45 sec', tags: ['obliques', 'core', 'bodyweight'], demoStyle: 'core',
  },
  {
    id: 'ex_shrug', slug: 'dumbbell-shrug', name: 'Dumbbell shrug', description: 'A direct upper-trapezius exercise using a controlled vertical shoulder path.',
    primaryMuscles: ['traps'], secondaryMuscles: ['forearms'], equipment: ['Dumbbells'], difficulty: 'beginner', category: 'hypertrophy', movementPattern: 'pull', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Stand tall with dumbbells at your sides.', 'Raise your shoulders straight toward your ears.', 'Pause briefly at the top.', 'Lower fully without rolling the shoulders.'], breathing: 'Exhale as the shoulders rise and inhale as they lower.', formTips: ['Keep your head neutral.', 'Use a straight up-and-down path.'], commonMistakes: ['Rolling the shoulders', 'Bending the elbows', 'Using momentum'], safetyTips: ['Use straps only if grip limits the target muscle.'], easierVariation: 'Band shrug', harderVariation: 'Paused heavy dumbbell shrug', setsRecommendation: '3–4 sets', repsRecommendation: '10–15 reps', restRecommendation: '75 sec', tags: ['traps', 'dumbbell', 'upper back'], demoStyle: 'pull',
  },
  {
    id: 'ex_row', slug: 'one-arm-dumbbell-row', name: 'One-arm dumbbell row', description: 'A supported horizontal pull for the lats, upper back, biceps, and rear shoulders.',
    primaryMuscles: ['lats', 'upper-back'], secondaryMuscles: ['biceps', 'rear-deltoids'], equipment: ['Dumbbell', 'Bench'], difficulty: 'beginner', category: 'strength', movementPattern: 'pull', trainingType: 'compound', locations: ['home', 'gym'],
    instructions: ['Support one hand and knee on a bench.', 'Brace your trunk and let the working arm hang long.', 'Drive the elbow toward your back pocket.', 'Lower until the shoulder blade can move forward naturally.'], breathing: 'Exhale as you row and inhale while lowering.', formTips: ['Keep the torso quiet.', 'Pull with the elbow rather than curling the weight.'], commonMistakes: ['Twisting the torso', 'Shrugging at the top', 'Shortening the stretch'], safetyTips: ['Keep the spine neutral and choose stable support.'], easierVariation: 'Band row', harderVariation: 'Three-point row without knee support', setsRecommendation: '3–4 sets', repsRecommendation: '8–12/side', restRecommendation: '75–90 sec', tags: ['back', 'lats', 'dumbbell'], demoStyle: 'pull',
  },
  {
    id: 'ex_lat_pulldown', slug: 'neutral-grip-lat-pulldown', name: 'Neutral-grip lat pulldown', description: 'A vertical pull that trains the lats through a comfortable shoulder path.',
    primaryMuscles: ['lats'], secondaryMuscles: ['biceps', 'upper-back'], equipment: ['Cable', 'Machine'], difficulty: 'beginner', category: 'hypertrophy', movementPattern: 'pull', trainingType: 'compound', locations: ['gym'],
    instructions: ['Secure your thighs under the pad and sit tall.', 'Grip the handles with palms facing each other.', 'Pull elbows down toward your sides.', 'Return to a full overhead stretch under control.'], breathing: 'Exhale on the pull and inhale during the return.', formTips: ['Keep the chest tall without leaning far back.', 'Let the shoulder blades rotate upward at the top.'], commonMistakes: ['Turning it into a row', 'Pulling behind the neck', 'Using body swing'], safetyTips: ['Avoid pulling behind the head.'], easierVariation: 'Half-kneeling band pulldown', harderVariation: 'Assisted pull-up', setsRecommendation: '3–4 sets', repsRecommendation: '8–12 reps', restRecommendation: '75–90 sec', tags: ['back', 'cable', 'lats'], demoStyle: 'pull',
  },
  {
    id: 'ex_bird_dog', slug: 'bird-dog', name: 'Bird dog', description: 'A spine-friendly stability drill for the lower back, glutes, and core.',
    primaryMuscles: ['lower-back'], secondaryMuscles: ['glutes', 'upper-abs'], equipment: ['Bodyweight', 'Mat'], difficulty: 'beginner', category: 'mobility', movementPattern: 'core', trainingType: 'compound', locations: ['home', 'gym'],
    instructions: ['Start on hands and knees with a neutral spine.', 'Brace gently, then extend one arm and the opposite leg.', 'Pause without rotating the pelvis.', 'Return and alternate sides.'], breathing: 'Exhale during the reach and inhale on return.', formTips: ['Reach long rather than high.', 'Keep the belt line level.'], commonMistakes: ['Over-arching the back', 'Rotating the hips', 'Rushing the reach'], safetyTips: ['Use a smaller leg range if the lower back feels compressed.'], easierVariation: 'Single-arm or single-leg reach', harderVariation: 'Elbow-to-knee bird dog', setsRecommendation: '2–3 sets', repsRecommendation: '6–10/side', restRecommendation: '30–45 sec', tags: ['back', 'mobility', 'bodyweight'], demoStyle: 'core',
  },
  {
    id: 'ex_hip_thrust', slug: 'hip-thrust', name: 'Hip thrust', description: 'A hip-extension exercise that loads the glutes strongly near full lockout.',
    primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings', 'lower-back'], equipment: ['Bench', 'Barbell'], difficulty: 'intermediate', category: 'hypertrophy', movementPattern: 'hinge', trainingType: 'compound', locations: ['gym'],
    instructions: ['Set your upper back against a stable bench.', 'Place the load across the hip crease and plant the feet.', 'Drive through the feet until hips are fully extended.', 'Lower under control while keeping the ribs down.'], breathing: 'Exhale into the lockout; inhale while lowering.', formTips: ['Finish by squeezing the glutes, not arching the back.', 'Keep shins close to vertical at the top.'], commonMistakes: ['Hyperextending the lower back', 'Pushing through the toes', 'Using an unstable bench'], safetyTips: ['Use a thick bar pad and secure the bench.'], easierVariation: 'Floor glute bridge', harderVariation: 'Paused hip thrust', setsRecommendation: '3–5 sets', repsRecommendation: '6–12 reps', restRecommendation: '90–120 sec', tags: ['glutes', 'barbell', 'hinge'], demoStyle: 'hinge',
  },
  {
    id: 'ex_goblet_squat', slug: 'goblet-squat', name: 'Goblet squat', description: 'A front-loaded squat that builds the quadriceps and teaches an upright, balanced pattern.',
    primaryMuscles: ['quadriceps'], secondaryMuscles: ['glutes', 'adductors', 'upper-abs'], equipment: ['Dumbbell', 'Kettlebell'], difficulty: 'beginner', category: 'strength', movementPattern: 'squat', trainingType: 'compound', locations: ['home', 'gym'],
    instructions: ['Hold one weight close to your chest.', 'Set your feet at a comfortable squat width.', 'Sit down between the hips while keeping the whole foot grounded.', 'Stand by driving the floor away.'], breathing: 'Inhale and brace before descending; exhale after the hardest part of the ascent.', formTips: ['Let knees track over toes.', 'Keep the weight close to your body.'], commonMistakes: ['Heels lifting', 'Knees collapsing inward', 'Losing the brace at the bottom'], safetyTips: ['Use a pain-free depth and stable footwear.'], easierVariation: 'Box squat', harderVariation: 'Double-kettlebell front squat', setsRecommendation: '3–4 sets', repsRecommendation: '8–15 reps', restRecommendation: '75–120 sec', tags: ['legs', 'squat', 'dumbbell'], demoStyle: 'squat',
  },
  {
    id: 'ex_rdl', slug: 'dumbbell-romanian-deadlift', name: 'Dumbbell Romanian deadlift', description: 'A hip hinge for the hamstrings, glutes, and back-body strength.',
    primaryMuscles: ['hamstrings'], secondaryMuscles: ['glutes', 'lower-back', 'forearms'], equipment: ['Dumbbells'], difficulty: 'intermediate', category: 'strength', movementPattern: 'hinge', trainingType: 'compound', locations: ['home', 'gym'],
    instructions: ['Stand tall with dumbbells close to the thighs.', 'Soften the knees and push the hips backward.', 'Lower until you feel a strong hamstring stretch without rounding.', 'Drive the hips forward and stand tall.'], breathing: 'Inhale and brace before hinging; exhale near the top.', formTips: ['Keep weights close to the legs.', 'Think long spine and hips back.'], commonMistakes: ['Turning it into a squat', 'Rounding the lower back', 'Leaning back at lockout'], safetyTips: ['Reduce the range if you cannot maintain spinal position.'], easierVariation: 'Dowel hip-hinge drill', harderVariation: 'Single-leg Romanian deadlift', setsRecommendation: '3–4 sets', repsRecommendation: '6–12 reps', restRecommendation: '90–120 sec', tags: ['hamstrings', 'hinge', 'dumbbell'], demoStyle: 'hinge',
  },
  {
    id: 'ex_calf_raise', slug: 'standing-calf-raise', name: 'Standing calf raise', description: 'A simple ankle plantar-flexion exercise for calf strength and size.',
    primaryMuscles: ['calves'], secondaryMuscles: [], equipment: ['Bodyweight', 'Dumbbells'], difficulty: 'beginner', category: 'hypertrophy', movementPattern: 'carry', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Stand tall with the balls of the feet secure.', 'Rise as high as comfortable onto the toes.', 'Pause briefly at the top.', 'Lower slowly into a gentle stretch.'], breathing: 'Breathe naturally through each repetition.', formTips: ['Keep pressure through the big toe and second toe.', 'Use a full, controlled range.'], commonMistakes: ['Bouncing', 'Rolling ankles outward', 'Using a very short range'], safetyTips: ['Hold stable support when using a step.'], easierVariation: 'Two-leg floor calf raise', harderVariation: 'Single-leg step calf raise', setsRecommendation: '3–5 sets', repsRecommendation: '10–25 reps', restRecommendation: '45–75 sec', tags: ['calves', 'bodyweight', 'lower body'], demoStyle: 'raise',
  },
  {
    id: 'ex_banded_march', slug: 'banded-hip-flexor-march', name: 'Banded hip-flexor march', description: 'A standing drill for hip-flexor strength and single-leg control.',
    primaryMuscles: ['hip-flexors'], secondaryMuscles: ['upper-abs', 'glutes'], equipment: ['Resistance band'], difficulty: 'intermediate', category: 'strength', movementPattern: 'lunge', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Loop a light band around both feet.', 'Stand tall and brace near a wall for balance.', 'Lift one knee without leaning backward.', 'Lower slowly and alternate sides.'], breathing: 'Exhale as the knee rises and inhale as it lowers.', formTips: ['Keep the standing hip tall.', 'Move only as high as you can without pelvic tilt.'], commonMistakes: ['Leaning back', 'Hiking the hip', 'Letting the band snap down'], safetyTips: ['Use support to prevent loss of balance.'], easierVariation: 'Seated knee lift', harderVariation: 'Cable hip-flexion march', setsRecommendation: '2–3 sets', repsRecommendation: '10–15/side', restRecommendation: '45 sec', tags: ['hips', 'band', 'mobility'], demoStyle: 'raise',
  },
  {
    id: 'ex_sumo_squat', slug: 'sumo-squat', name: 'Sumo squat', description: 'A wide-stance squat that trains the thighs, glutes, and hip adductors.',
    primaryMuscles: ['adductors', 'quadriceps'], secondaryMuscles: ['glutes'], equipment: ['Bodyweight', 'Dumbbell'], difficulty: 'beginner', category: 'strength', movementPattern: 'squat', trainingType: 'compound', locations: ['home', 'gym'],
    instructions: ['Take a comfortable wide stance with toes turned slightly out.', 'Brace and sit down between the hips.', 'Track the knees in line with the toes.', 'Stand by pressing the whole foot into the floor.'], breathing: 'Inhale down and exhale through the standing phase.', formTips: ['Choose width based on hip comfort.', 'Stay tall through the chest.'], commonMistakes: ['Forcing an extreme stance', 'Knees falling inward', 'Shifting onto the toes'], safetyTips: ['Narrow the stance if the groin or hips feel pinched.'], easierVariation: 'Wide-stance box squat', harderVariation: 'Heavy goblet sumo squat', setsRecommendation: '3–4 sets', repsRecommendation: '10–15 reps', restRecommendation: '75–90 sec', tags: ['adductors', 'legs', 'squat'], demoStyle: 'squat',
  },
  {
    id: 'ex_lateral_walk', slug: 'band-lateral-walk', name: 'Band lateral walk', description: 'A lateral stepping drill for the hip abductors and pelvic control.',
    primaryMuscles: ['abductors'], secondaryMuscles: ['glutes', 'quadriceps'], equipment: ['Resistance band'], difficulty: 'beginner', category: 'strength', movementPattern: 'lunge', trainingType: 'isolation', locations: ['home', 'gym'],
    instructions: ['Place a light band above the knees or at the ankles.', 'Sit into a shallow athletic stance.', 'Step sideways while keeping steady band tension.', 'Bring the trailing foot in without letting the knees collapse.'], breathing: 'Breathe steadily throughout the set.', formTips: ['Keep toes pointing mostly forward.', 'Take small, deliberate steps.'], commonMistakes: ['Dragging the trailing foot', 'Rocking the torso', 'Letting the knees cave inward'], safetyTips: ['Start with the band above the knees for an easier, more stable setup.'], easierVariation: 'Standing band abduction', harderVariation: 'Low monster walk', setsRecommendation: '2–3 sets', repsRecommendation: '10–15 steps/side', restRecommendation: '45 sec', tags: ['hips', 'band', 'glutes'], demoStyle: 'squat',
  },
];

export const EXERCISE_BY_SLUG = Object.fromEntries(EXERCISES.map((exercise) => [exercise.slug, exercise])) as Record<string, Exercise>;

export const EQUIPMENT_OPTIONS = ['Bodyweight', 'Dumbbells', 'Barbell', 'Resistance band', 'Cable', 'Machine', 'Kettlebell', 'Bench', 'Mat'];
